config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  # Authentication Related Paths
  resource :registration
  resource :session
  resource :password_reset
  resource :password

  resources :posts

  root "post#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 10000 }

  belongs_to :user
  belongs_to :post
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  enum :status, { unseen: 0, seen: 1, resolved: 2 }

  validates :user_id, presence: true

  validates :title, presence: true, length: { maximum: 300 }
  validates :content, presence: true, length: { maximum: 40000 }
  validates :status, presence: true, inclusion: { in: statuses.keys, message: " is not valid" }

  belongs_to :user
  has_many :reactions
  has_many :comments
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates :reaction, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  normalizes :email, with: ->(email) { email.strip.downcase }

  validates :username, presence: true, length: { maximum: 20 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 320 }, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } # TODO: verify if this really is an email, with the @ and everything
  validates :role, presence: true, inclusion: { in: [ 0, 1 ], message: "You do not have a valid role" }

  has_many :posts
  has_many :reactions
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  private

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/main_controller.rb
# temp main menu
class MainController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def index
  #   @posts = Post.all
  # end
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.status = 1
    @post.user_id = current_user.id
    @post.save
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)

    if @user.save
      login @user
      redirect_to root_path
    else
      raise
      render :new, status: :unprocessable_entity
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :role)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if user = User.authenticate_by(login_params)
      login user
      redirect_to root_path, notice: "You have signed successfully"
    else
      flash[:alert] = "Invalid email or password"
      @user = User.new
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out"
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sample Anonymask" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>

    <% if user_signed_in? %>
      <%# TODO: Low priority, skim these things that create html tags for me %>
      <%= link_to "Edit Password", "#" %>
      <%= button_to "Log out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_registration_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Welcome To Our Homepage!!</h1>

app/views/posts/edit.html.erb
<h1>Edit Post GRABEH!!</h1>

<%= form_with model: @post do |form| %>
        <div>
                <%= form.label :title %>
                <%= form.text_field :title %>
        </div>
        <div>
                <%= form.label :content %>
                <%= form.text_field :content %>
        </div>

        <div>
                <%= form.submit "Edit Post" %>
        </div>
<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <div>
      <a href="/posts/<%= post.id %>">
        <%= post.title %>
      </a>
      <p><%= post.content %></p>
    </div>
    <br />
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post GRABEH!!</h1>

<%= form_with model: @post do |form| %>
        <div>
                <%= form.label :title %>
                <%= form.text_field :title %>
        </div>
        <div>
                <%= form.label :content %>
                <%= form.text_field :content %>
        </div>

        <div>
                <%= form.submit "Post" %>
        </div>
<% end %>

app/views/posts/show.html.erb
<div>
        <h1><%= @post.title %></h1>
        <p><%= @post.content %></p>
        <%= link_to "Back", posts_path %>
        <%= link_to "Edit", edit_post_path(@post) %>
        <%= button_to "Delete", @post, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

</div>